baseURL = 'https://kiryl-volkau.github.io/kiryl-blog/'
languageCode = 'en-us'
title = 'Kiryl Volkau'
theme = 'LoveIt'
languageName = "English"

[pagination]
    disableAliases = false
    pagerSize = 10
    path = "page"

[menu]
    [[menu.main]]
        weight = 1
        identifier = "home"
        pre = ""
        post = ""
        name = "Home"
        url = "/home/"
        title = ""
    [[menu.main]]
        weight = 2
        identifier = "post"
        pre = ""
        post = ""
        name = "Posts"
        url = "/posts/"
        title = ""

[params]
    title = "Kiryl Volkau"
    defaultTheme = "auto"
    gitRepo = "https://github.com/kiryl-volkau/kiryl-blog"
    description = "Kiryl Volkau Blog"

    [params.author]
        name = "Kiryl Volkau"
        email = ""
        link = ""

    [params.footer]
        enable = true
        author = true
        since = 2025

    [params.social]
        GitHub = "https://github.com/kiryl-volkau"
        Linkedin = "https://www.linkedin.com/in/kvolkau/"
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe = true

    [markup.highlight]
        noClasses = false
#[caches]
#    [caches.images]
#        dir = ':cacheDir/images'

[outputs]
home = ["HTML", "RSS", "JSON"]