baseURL = 'https://kiryl-volkau.github.io/kiryl-blog/'
languageCode = 'en-us'
title = 'Kiryl Volkau Blog'
theme = 'PaperMod'

[params]
ShowToc = true
ShowBreadCrumbs = true
ShowReadingTime = true
homeInfoParams = { Title = "Hi, I'm Kiryl!", Content = "Welcome to my blog. I write about software engineering." }

[caches]
    [caches.images]
        dir = ':cacheDir/images'

[outputs]
home = ["HTML", "RSS", "JSON"]