baseURL = 'https://kiryl-volkau.github.io/kiryl-blog/'
languageCode = 'en-us'
title = 'Kiryl Volkau Blog'
theme = 'PaperMod'
paginate = 10

[params]
ShowToc = true
ShowBreadCrumbs = true
ShowReadingTime = true
homeInfoParams = { Title = "Hi, I'm Kiryl!", Content = "Welcome to my blog. I write about software engineering." }

[outputs]
home = ["HTML", "RSS", "JSON"]