baseURL = 'https://kirillvolkov.com'
languageCode = 'en-us'
title = 'Kiryl Volkau'
theme = 'LoveIt'
languageName = "English"

[pagination]
    disableAliases = false
    pagerSize = 10
    path = "page"

[menu]
    [[menu.main]]
        weight = 1
        identifier = "home"
        pre = ""
        post = ""
        name = "Home"
        url = "/"
        title = ""
    [[menu.main]]
        weight = 2
        identifier = "post"
        pre = ""
        post = ""
        name = "Posts"
        url = "/posts/"
        title = ""

[params]
    title = "Kiryl Volkau"
    defaultTheme = "auto"
    gitRepo = "https://github.com/kiryl-volkau/kiryl-blog"
    description = "Kiryl Volkau Blog"
    socialInHeader = true
    socialInFooter = true
    dateFormat = "02-01-2006"

    [params.home]
        rss = 10

        [params.home.profile]
            enable = true
            social = true
            title = "Kiryl Volkau"
            subtitle = "Senior Software Engineer | Java | Spring Enthusiast"

        [params.home.posts]
            enable = true
            paginate = 6

    [params.author]
        name = "Kiryl Volkau"

    [params.header]
        [params.header.title]
            name = "Kiryl Volkau"

    [params.footer]
        enable = true
        author = true
        since = 2025

    [params.social]
        GitHub = "kiryl-volkau"
        Linkedin = "kvolkau"

    [params.analytics]
        enable = true

        [params.analytics.google]
            id = "G-JWLM01WEG5"
            anonymizeIP = true

    [params.page.comment]
        enable = true

        [params.page.comment.giscus]
            enable = true
            repo = "kiryl-volkau/kiryl-blog"
            repoId = "R_kgDOPDcqVg"
            category = "Announcements"
            categoryId = "DIC_kwDOPDcqVs4Cs3uf"
            lang = ""
            mapping = "pathname"
            reactionsEnabled = "1"
            emitMetadata = "0"
            inputPosition = "bottom"
            lazyLoading = false
            lightTheme = "light"
            darkTheme = "dark"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe = true

    [markup.highlight]
        noClasses = false
#[caches]
#    [caches.images]
#        dir = ':cacheDir/images'

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML"]